name: energy
author: vu-ase
source: https://github.com/VU-ASE/energy
version: 0.0.1
description: A service that publishes energy data of the Rover

commands:
  build: make build
  run: ./bin/energy

inputs:

outputs:
  - energy

configuration:
  - name: updates-per-second
    type: number
    value: 5
    tunable: true
